apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petclinic-service.name" . }}
  labels:
    {{- include "petclinic-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "petclinic-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "petclinic-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "petclinic-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- if .Values.configServer.enabled }}
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:{{ .Values.configServer.url }}"
            {{- end }}
            {{- if .Values.eurekaServer.enabled }}
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "{{ .Values.eurekaServer.url }}"
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
