apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-prod-config-server
  namespace: argocd
  labels:
    project: petclinic
    environment: prod
    service: config-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: petclinic
  source:
    repoURL: https://github.com/petclinic-project/petclinic-platform.git
    targetRevision: HEAD
    path: petclinic-eks-deployment/helm/petclinic-service
    helm:
      releaseName: config-server
      valueFiles:
        - ../../helm-values/config-server.yaml
        - ../../helm-values/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod
  # NO automated block — prod requires manual approval before sync
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
