apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-dev-api-gateway
  namespace: argocd
  labels:
    project: petclinic
    environment: dev
    service: api-gateway
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: petclinic
  source:
    repoURL: https://github.com/petclinic-project/petclinic-microservices.git
    targetRevision: HEAD
    path: helm/petclinic-service
    helm:
      releaseName: api-gateway
      valueFiles:
        - ../../helm-values/api-gateway.yaml
        - ../../helm-values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
